sudo: false
language: ruby 
rvm:
  - 2.4.4

before_install:
  - sudo apt-get install lftp

deploy:
  - provider: script
    skip_cleanup: true
    script: lftp -e 'mirror -R -v _site public_html; bye' -u $DEPLOY_USER,$DEPLOY_PASS $DEPLOY_SERVER
    on:
      branch: source
